-- Insert all services from the mock data in src/lib/services.ts
INSERT INTO services (title, details, time, category, price) VALUES
('Business Consultation', 'One-on-one consultation for your business needs. Our expert consultants will help you identify opportunities for growth, optimize operations, and develop strategic plans tailored to your business goals.', '60 min', 'consulting', 99.00),
('Haircut & Styling', 'Professional haircut and styling service. Our experienced stylists will provide a personalized experience, from consultation to finishing touches, ensuring you leave with a look that suits your style and personality.', '45 min', 'beauty', 49.00),
('Home Repair', 'General home repair and maintenance. Our skilled technicians can handle a wide range of repairs, from fixing leaky faucets to patching drywall, helping you maintain your home in top condition.', '120 min', 'maintenance', 129.00),
('Legal Consultation', 'Professional legal advice for various matters. Our attorneys provide clear guidance on legal issues affecting individuals and businesses, helping you navigate complex legal situations with confidence.', '90 min', 'consulting', 149.00),
('Massage Therapy', 'Relaxing full-body massage to relieve stress. Our certified massage therapists use various techniques to reduce muscle tension, improve circulation, and promote overall well-being.', '60 min', 'beauty', 79.00),
('Plumbing Service', 'Professional plumbing repair and installation. Our licensed plumbers can diagnose and fix issues with your plumbing system, install new fixtures, and provide preventative maintenance to avoid future problems.', '90 min', 'maintenance', 109.00),
('Financial Planning', 'Comprehensive financial planning and advice to secure your future. Our financial advisors help you create personalized strategies for retirement, investment, and saving goals.', '120 min', 'consulting', 179.00),
('Facial Treatment', 'Rejuvenating facial treatment for glowing skin. Our estheticians use premium products and techniques to cleanse, exfoliate, and hydrate your skin for a refreshed appearance.', '75 min', 'beauty', 89.00),
('Electrical Repairs', 'Professional electrical repair and installation services. Our licensed electricians can handle everything from wiring issues to installing new fixtures safely and efficiently.', '100 min', 'maintenance', 119.00); 